### ISSUE TITLE
Feature Request: Update URL for current app when running

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/shinylive#128]
It took me a long time to learn **not to** copy the URL of the current page to share an app in editor mode because the URL will point to the initially loaded app and not the current version being edited.

It'd be helpful if the URL were updated in editor mode to reflect the current state of the app each time it is re-run via the Play button or <kbd>Cmd/Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Enter</kbd>.

**Comment by wch** [comment]
Good idea - originally I had played around with updating the URL as the user edited the code, with some debouncing, but especially for larger apps with data files, the blocking of the UI as the JS thread encoded the data made for a bad experience. Encoding only when the user re-runs the app would make this much less of a problem.

A couple of thoughts:
- It would be good to do the encoding in a web worker, because for the encoding time can be non-negligible for larger apps.
- For very large apps, it might be still problematic to encode the app and put it in the URL every time someone re-runs it. In that case, maybe we should put something else in the URL bar to indicate that the user should click on the Share button to get the URL?
