### ISSUE TITLE
[httpuv] runStaticServer function is not available

### ISSUE THREAD

**Issue by RamiKrispin** [posit-dev/shinylive#67]
I am trying to run the example on the readme, and I got the following error:

```r 
httpuv::runStaticServer("site", port=8008)
Error: 'runStaticServer' is not an exported object from 'namespace:httpuv'
```

It seems that the `runStaticServer` function does not available on the [CRAN](https://cran.r-project.org/web/packages/httpuv/httpuv.pdf) (`1.6.11`) docs or namespace. I tried to install directly from the package Github and got the same error:

```r
packageVersion("httpuv")
[1] ‘1.6.11.9000’
```

Thanks!

**Comment by gadenbuie** [comment]
Thanks Rami, this is tracked in https://github.com/posit-dev/r-shinylive/issue/7 and the docs should be fixed by https://github.com/posit-dev/r-shinylive/pull/6. One thing to check is to make sure you restarted your R session after installing the dev version of httpuv. If you did, then please follow up in the linked issue, thanks!

**Comment by RamiKrispin** [comment]
Thanks @gadenbuie for the prompt response. Yes, the restart does the job with version `1.6.11.9000`!
